version: "3.8"
services:
    shopper:
        build:
            context: .
            cache_from:
                - python:3.8-alpine
        image: shopper:dev
        ports:
            - "80:8000"
        volumes:
            - ./src:/srv/app
        depends_on:
            - db
            - phpmyadmin

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8080:80"
        depends_on:
            - db

    db:
        image: mariadb:10.5
        volumes:
            - shopper-db:/var/lib/mysql
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
            MYSQL_USER: shopper
            MYSQL_PASSWORD: shopper
            MYSQL_DATABASE: shopper

volumes:
    shopper-db: